export const GET_USERS = "GET_POSTS";
export const GET_USERS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_USERS_FAIL = "GET_POSTS_FAIL";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";